### ISSUE TITLE
nightwatch

### ISSUE THREAD

**Issue by Lars-Nijboer** [Kuniwak/html-dnd#2] opened 2016-04-11 14:21 UTC
I cant get drag and drop to work in nightwatch. It selects the target just fine, but afterwards it wont move to the destination to 'mouseButtonUp()

**Comment by Kuniwak** [comment] 2016-04-11 15:18
Thank you for the bug report.

Could you show your `nightwatch.json` to me?

**Comment by Lars-Nijboer** [comment] 2016-04-11 15:37
{
   "src_folders": [
      "tests"
   ],
   "output_folder": "reports",
   "custom_commands_path": "custom-commands",
   "custom_assertions_path": "./node_modules/nightwatch-commands/assertions",
   "page_objects_path": "pages",
   "globals_path": "globals.js",
   "selenium": {
      "start_process": true,
      "server_path": "./bin/selenium-server-standalone-2.52.0.jar",
      "log_path": "",
      "host": "127.0.0.1",
      "port": 4444,
      "cli_args": {
         "webdriver.chrome.driver": "./bin/chromedriver"
      }
   },
   "test_settings": {
      "default": {
         "launch_url": "http://localhost",
         "selenium_port": 4444,
         "selenium_host": "localhost",
         "silent": true,
         "screenshots": {
            "enabled": true,
            "on_failure": true,
            "on_error": true,
            "path": "test/functional/reports/screenshots"
         },
         "desiredCapabilities": {
            "browserName": "firefox",
            "javascriptEnabled": true,
            "acceptSslCerts": true
         }
      },
      "chrome": {
         "screenshots": {
            "enabled": true,
            "path": /test/functional/reports/screenshots"
         },
         "desiredCapabilities": {
            "browserName": "chrome",
            "javascriptEnabled": true,
            "acceptSslCerts": true
         }
      },
      "firefox": {
         "screenshots": {
            "enabled": true,
            "path": "/test/functional/reports/screenshots"
         },
         "desiredCapabilities": {
            "browserName": "firefox"
         }
      }
   }
}

2016-04-11 17:18 GMT+02:00 Kuniwak notifications@github.com:

**Comment by Lars-Nijboer** [comment] 2016-04-11 15:43
'step 4: draganddrop': function (browser) {
   browser
      .execute(dragAndDrop, ['#main-container > div > div >
div.fc-region-container.fc-container.ui-sortable > div > div.card-list

> div.fc-card-list-container > div > div > div:nth-child(1) >
> div.panel-body.js-column-container > div > div >
> div.fc-region-container.fc-container.ui-sortable > div:nth-child(2) >
> div:nth-child(2)', '#main-container > div > div >
> div.fc-region-container.fc-container.ui-sortable > div > div.card-list
> div.fc-card-list-container > div > div > div:nth-child(2) >
> div.panel-heading'])        // .waitForElementVisible('#main-container
> div > div > div.fc-region-container.fc-container.ui-sortable > div >
> div.card-list > div.fc-card-list-container > div > div >
> div:nth-child(1) > div.panel-body.js-column-container > div > div >
> div.fc-region-container.fc-container.ui-sortable > div:nth-child(2) >
> div:nth-child(2)', globalVars.timeout)

```
  // .moveToElement('#main-container > div > div >
```

div.fc-region-container.fc-container.ui-sortable > div > div.card-list

> div.fc-card-list-container > div > div > div:nth-child(1) >
> div.panel-body.js-column-container > div > div >
> div.fc-region-container.fc-container.ui-sortable > div:nth-child(2) >
> div:nth-child(2)', 1, 1)
>       // .mouseButtonDown()
>       // .moveToElement('div.panel-cards-list:nth-child(2) >
> div:nth-child(2)', 1, 1)
>       // .moveToElement('div.panel-cards-list:nth-child(2) >
> div:nth-child(2)', 5, -5)
>       // .pause(5000)
>       // .mouseButtonUp()
>       .end();
>          }

2016-04-11 17:37 GMT+02:00 Lars Nijboer l.nijboer@fortes.nl:

**Comment by Kuniwak** [comment] 2016-04-12 12:03
Thanks you, @ForteDell .

I have a question.
How do you implement your drag and drop feature?
1. Using [HTML Drag and Drop API](https://developer.mozilla.org/en-US/docs/Web/API/HTML_Drag_and_Drop_API)
   
   ``` html
   <body>
    <p id="p1" draggable="true" ondragstart="dragstart_handler(event);">This element is draggable.</p>
   </body>
   ```
2. Using a library for drag and drops such as [jQuery UI Draggable](https://jqueryui.com/draggable/)
   
   ``` javascript
   $(function() {
     $( "#draggable" ).draggable();
   });
   ```

This is a important question because html-dnd can simulate only the first approach.

**Comment by sunyatasattva** [comment] 2016-04-29 16:29
I also have a problem on making the patch work on Nightwatch. It's different, though, so I don't know if you want me to open a separate issue. It gives me this error:

```
value: 
   { message: 'java.lang.String cannot be cast to java.util.List',
     suppressed: [],
     localizedMessage: 'java.lang.String cannot be cast to java.util.List',
     cause: null,
     class: 'java.lang.ClassCastException',
     hCode: 413477975,
     screen: null },
  state: 'unhandled error',
  class: 'org.openqa.selenium.remote.Response',
  hCode: 1298472086 }
```

Any idea? I am using a minimal test case:

```
var dragAndDrop = require('html-dnd').codeForSelectors;

module.exports = {
  'drag and drop': function(browser) {
    browser
      .url('http://html5demos.com/drag')
      .execute(dragAndDrop, '#one', '#bin')
      .pause(3000) // Just to see if it really happened
      .end();
  }
};
```

**Comment by Kuniwak** [comment] 2016-04-29 17:59
Sorry for my late reply.

@sunyatasattva 

The example for nightwatch in README had been wrong (#5).
Try this:

``` javascript
var dragAndDrop = require('html-dnd').codeForSelectors;

module.exports = {
  'drag and drop': function(browser) {
    browser
      .url('http://html5demos.com/drag')
      .execute(dragAndDrop, ['#one', '#bin'])
      .pause(3000) // Just to see if it really happened
      .end();
  }
};
```

**Comment by sunyatasattva** [comment] 2016-05-02 12:44
Hello @Kuniwak thank you for your reply! Indeed this solves the error I mentioned, however, drag and drop still doesn't work. Have you tried the code you posted yourself (I mean, with a real drag and drop demo such as the one linked)? Does that work for you?

It doesn't do anything in my case, unfortunately.

By the way, thank you for your work: this is an extremely important issue for the task I am currently working on, as our application depends mainly on drag and drop. Thanks for all your effort.

**Comment by Kuniwak** [comment] 2016-05-02 17:12
@sunyatasattva I added compatibility tests for Nightwatch.js (#7), but it seemed working fine.

But I do not test on http://html5demos.com/drag yet.
I'm gonna check it soon.

**Comment by Kuniwak** [comment] 2016-05-02 19:01
Oh, I misunderstood the spec of [Drag data stores](https://html.spec.whatwg.org/multipage/interaction.html).

I'm gonna fix it. Please wait for some days.

**Comment by sunyatasattva** [comment] 2016-05-03 19:05
@Kuniwak Thanks for your quick reply! Can you quickly explain what is the difference between the html5demos and you own test?

**Comment by Kuniwak** [comment] 2016-05-03 21:48
html-dnd should use a shared DataTransfer object between a drag-and-drop operation, but html-dnd does not do it:

``` javascript
  var dragstartEvent = dnd.createEventWithDataTransfer(
    dnd.EventType.DRAG_START);
  dispatchEvent(draggable, dragstartEvent);

  // Using a new DataTransfer object...
  var dropEvent = dnd.createEventWithDataTransfer(dnd.EventType.DROP);
  dispatchEvent(droppable, dropEvent);

  // Using a new DataTransfer object...
  var dragendEvent = dnd.createEventWithDataTransfer(dnd.EventType.DRAG_END);
  dispatchEvent(draggable, dragendEvent);
```

**Comment by Kuniwak** [comment] 2016-05-03 22:58
I confirmed that it was fixed on http://html5demos.com/drag .

@sunyatasattva Please upgrade to `html-dnd@1.0.4` and retry it.

**Comment by sunyatasattva** [comment] 2016-05-04 15:07
Thanks @Kuniwak ! You single-handedly saved our project! Do you accept tips or donations?

**Comment by Kuniwak** [comment] 2016-05-08 13:23
@ForteDell Hi, did you resolve this problem?

**Comment by Lars-Nijboer** [comment] 2016-05-09 15:23
Unfortunately not for me, but I'm more and more inclined to think it is
because of the specific page I'm testing. So let's call it resolved for now.

2016-05-08 15:23 GMT+02:00 Kuniwak notifications@github.com:

**Closed as completed** 2016-05-09 15:24 UTC
Labels: Bug, Question

**Comment by Poornakiruthika** [comment] 2017-07-24 08:18
How can we achieve drag and drop if the drag-gable and droppable has no Id?
